# Generated by Django 3.0.3 on 2020-03-18 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=20, verbose_name='课号')),
                ('course_name', models.CharField(max_length=20, verbose_name='课名')),
                ('course_score', models.IntegerField(verbose_name='学分')),
                ('course_term', models.CharField(max_length=20, verbose_name='学期')),
                ('course_times', models.CharField(max_length=20, verbose_name='上课时间')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentTable',
            fields=[
                ('department_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='院系号')),
                ('department_name', models.CharField(max_length=20, verbose_name='院系名称')),
                ('department_address', models.CharField(max_length=20, verbose_name='地址')),
                ('department_phone_number', models.CharField(max_length=20, verbose_name='联系电话')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherTable',
            fields=[
                ('teacher_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('teacher_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('teacher_gender', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=20, verbose_name='性别')),
                ('teacher_birth', models.CharField(max_length=20, verbose_name='出生日期')),
                ('teacher_degree', models.CharField(max_length=20, verbose_name='学历')),
                ('teacher_salary', models.IntegerField(verbose_name='基本工资')),
                ('teacher_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mproject.DepartmentTable', verbose_name='所属院系')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('student_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('student_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('student_gender', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=20, verbose_name='性别')),
                ('student_birth', models.CharField(max_length=20, verbose_name='出生日期')),
                ('student_native_place', models.CharField(max_length=20, verbose_name='籍贯')),
                ('student_phone_number', models.CharField(max_length=20, verbose_name='手机号码')),
                ('student_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mproject.DepartmentTable', verbose_name='所属院系')),
            ],
        ),
        migrations.CreateModel(
            name='EventTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_usual_results', models.IntegerField(blank=True, null=True, verbose_name='平时成绩')),
                ('event_exam_results', models.IntegerField(blank=True, null=True, verbose_name='考试成绩')),
                ('event_total_results', models.IntegerField(blank=True, null=True, verbose_name='总评成绩')),
                ('event_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mproject.CourseTable', verbose_name='课程')),
                ('event_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mproject.StudentTable', verbose_name='选课学生')),
            ],
        ),
        migrations.AddField(
            model_name='coursetable',
            name='course_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mproject.TeacherTable', verbose_name='授课教师'),
        ),
        migrations.AlterUniqueTogether(
            name='coursetable',
            unique_together={('course_number', 'course_teacher')},
        ),
    ]
